# Generated by Django 5.0 on 2026-01-25 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warranties', '0005_warranty_warranty_period_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('30_days', '30 Days Before Expiry'), ('20_days', '20 Days Before Expiry'), ('10_days', '10 Days Before Expiry'), ('3_days', '3 Days Before Expiry'), ('2_days', '2 Days Before Expiry'), ('1_day', '1 Day Before Expiry'), ('expired', 'Warranty Expired')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('warranty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='warranties.warranty')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'), models.Index(fields=['warranty', 'notification_type'], name='notificatio_warrant_948c90_idx')],
            },
        ),
    ]
