# Generated by Django 5.0 on 2026-01-17 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Home Appliances', 'Home Appliances'), ('Furniture', 'Furniture'), ('Automotive', 'Automotive'), ('Accessories', 'Accessories'), ('Other', 'Other')], max_length=50)),
                ('purchase_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('document', models.CharField(blank=True, max_length=500, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Warranty',
                'verbose_name_plural': 'Warranties',
                'db_table': 'warranties',
                'ordering': ['-created_at'],
            },
        ),
    ]
