# Generated by Django 5.0 on 2026-01-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warranty',
            name='warranty_period',
            field=models.IntegerField(default=12, help_text='Warranty duration in months'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
