# Generated by Django 5.0 on 2026-01-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranties', '0002_warranty_warranty_period_alter_warranty_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warranty',
            name='document',
        ),
        migrations.AddField(
            model_name='warranty',
            name='receipt_file',
            field=models.FileField(blank=True, help_text='Uploaded receipt/warranty document', null=True, upload_to='receipts/%Y/%m/'),
        ),
    ]
