# Generated by Django 5.0 on 2026-01-18 16:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranties', '0003_remove_warranty_document_warranty_receipt_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='warranty',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique token for public sharing', unique=True),
        ),
    ]
