# Generated by Django 5.0 on 2026-01-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranties', '0004_warranty_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='warranty',
            name='warranty_period_unit',
            field=models.CharField(choices=[('days', 'Days'), ('months', 'Months')], default='months', help_text='Unit for warranty period (days or months)', max_length=10),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='warranty_period',
            field=models.IntegerField(default=12, help_text='Warranty duration in months or days'),
        ),
    ]
